# Generated by Django 4.2 on 2026-02-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], default='student', max_length=20),
        ),
    ]
